server:
  port: 9002

spring: 
 datasource:
    url: jdbc:postgresql://localhost:5432/projeto-api
    username: postgres
    password: postgres

 jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc: 
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true


